[build]
  publish = "dist/tenis_progres"
  command = "npm install --force && ng build --configuration production"

[build.environment]
  NODE_VERSION = "16.14.0"  # Asegúrate de usar una versión compatible de Node.js